---
- hosts: local
  tasks:
  - name: enable rpmfusion free repo
    become: yes
    dnf: name=https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm state=present
  - name: enable rpmfusion nonfree repo
    become: yes
    dnf: name=https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm state=present
  - name: update all packages
    become: yes
    dnf: name=* state=latest