---
- hosts: all
  become: yes
  tasks:
    - name: ensure config manager is installed
      ansible.builtin.dnf:
        name: "dnf-command(config-manager)"
        state: latest
    - name: Add GitHub tooling repo"
      ansible.builtin.yum_repository:
        name: github-tools
        description: Github tooling repo
        baseurl: "https://cli.github.com/packages/rpm"
        gpgkey: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x23F3D4EA75716059"
    - name: Install github tooling
      ansible.builtin.dnf:
        name: "gh"
        state: latest
