---
- hosts: all
  tasks:
  - name: ensure that all dependencies are installed at the latest version
    become: yes
    package: state=latest name={{ item }}
    with_items:
      - i3
      - i3lock
  - name: ensure file that the config directory has the right permisions
    become: yes
    file:
      path: /home/{{ ansible_env.USERNAME }}/.config/i3
      state: directory
      owner: "{{ ansible_env.USERNAME }}"
      group: "{{ ansible_env.USERNAME }}"
      mode: 0755
  - name: copy main config
    template: src=../config/configuration/i3.tpl dest=/home/{{ ansible_env.USERNAME }}/.config/i3/config
