---
- hosts: all
  tasks:
  - name: ensure i3 is installed at the latest version
    become: yes
    dnf: name=i3 state=latest
  - name: ensure i3lock is installed at the latest version
    become: yes
    dnf: name=i3lock state=latest
  - name: copy main config
    template: src=../config/configuration/i3.tpl dest=/home/l33tname/.config/i3/config
