---
- hosts: all
  tasks:
  - name: ensure that all dependencies are installed at the latest version
    become: yes
    package: state=latest name={{ item }}
    with_items:
      - i3
      - i3lock
      - terminator
  - name: ensure file that the script has the right permisions
    become: yes
    file: 
      path: /home/{{ ansible_env.USER }}/.config/i3 
      state: directory 
      owner: "{{ ansible_env.USER }}" 
      group: "{{ ansible_env.USER }}" 
      mode: 0755
  - name: copy main config
    template: src=../config/configuration/i3.tpl dest=/home/{{ ansible_env.USER }}/.config/i3/config
