---
- hosts: all
  tasks:
  - name: keep the last 6 kernel
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/dnf/dnf.conf
      regexp: '^installonly_limit='
      line: installonly_limit=6
