---
- hosts: all
  tasks:
  # the private key needs to be imported with gpg --import 
  # for this to work 
  - name: ensure pass is installed at the latest version
    become: yes
    package: name=pass state=latest
  - name: ensure the sway bin directory exists
    file: path={{ ansible_env.HOME }}/.config/sway/bin state=directory
  - name: copy the rofi config script
    template: src=../config/scripts/rofi_pass.tpl dest={{ ansible_env.HOME  }}/.config/sway/bin/rofi_pass.sh
  - name: ensure file that the script has the right permisions
    file: path={{ ansible_env.HOME }}/.config/sway/bin/rofi_pass.sh owner={{ ansible_env.USERNAME }} group={{ ansible_env.USERNAME }} mode=0755
  - name: ensure a pinentry tool is installed
    become: yes
    package: name=pinentry state=latest
  - name: ensure the gpg config directory exists
    file: path={{ ansible_env.HOME }}/.gnupg state=directory
  - name: force gpg to use the qt version
    copy:
      dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
      content: |
        pinentry-program /usr/bin/pinentry-qt
  - name: reload gpg agent
    ansible.builtin.command: gpg-connect-agent reloadagent /bye
