---
- hosts: all
  become: yes
  vars:
      destdir: /usr/local/src/polybar
  tasks:
  - name: ensure that all dependencies are installed at the latest version
    package: state=latest name={{ item }}
    with_items:
            # development
            - cmake
            - clang
            - cairo-devel
            - xcb-proto
            - xcb-util-devel
            - xcb-util-wm-devel
            - xcb-util-image-devel
            - xcb-util-cursor-devel
            - wireless-tools-devel
            # i3
            - i3-ipc
            - jsoncpp-devel
            # Volume
            - alsa-lib-devel
            - pulseaudio-libs-devel
            # curl
            - libcurl-devel
  - name: clone polybar
    git:
        repo: https://github.com/jaagr/polybar.git
        dest: "{{ destdir }}"
        update: yes
        force: yes
        version: 77d36b959df0ce5e129044697da2c306c355abeb
  - name: ensure that the build dir exist
    file: path={{ destdir }}/build state=directory
  - name: configure polybar
    command: >
        cmake -DCMAKE_C_COMPILER="clang"
              -DCMAKE_CXX_COMPILER="clang++"
              -DCMAKE_BUILD_TYPE="RELEASE"
              -DENABLE_ALSA:BOOL="ON"
              -DENABLE_I3:BOOL="ON"
              -DENABLE_MPD:BOOL="OFF"
              -DENABLE_NETWORK:BOOL="ON"
              -DENABLE_CURL:BOOL="ON"
              -DBUILD_IPC_MSG:BOOL="ON" ..
    args:
        chdir: "{{ destdir }}/build"
  - name: build polybar
    command: make chdir={{ destdir }}/build
  - name: install polybar
    command: make install chdir={{ destdir }}/build
  # configuration
  - name: ensure the i3 directory exists
    file: path=/home/{{ ansible_env.USER }}/.config/i3 state=directory
  - name: copy the config
    template: src=../config/configuration/polybar.tpl dest=/home/{{ ansible_env.USER  }}/.config/i3/polybar.conf
  - name: ensure the i3 bin directory exists
    file: path=/home/{{ ansible_env.USER }}/.config/i3/bin state=directory
  - name: copy the wrapper script for i3
    template: src=../config/scripts/run_polybar.tpl dest=/home/{{ ansible_env.USER  }}/.config/i3/bin/run_polybar.sh
  - name: ensure file that the script has the right permisions
    file: path=/home/{{ ansible_env.USER }}/.config/i3/bin/run_polybar.sh owner={{ ansible_env.USER }} group={{ ansible_env.USER }} mode=0755

