# setup screenshot script
---
- hosts: all
  tasks:
  - name: ensure flameshot is installed at the latest version
    become: yes
    package: state=latest name={{ item }}
    with_items:
      - flameshot
  - name: ensure grim shot is installed since flameshot does not work well on wayland
    become: yes
    package: state=latest name={{ item }}
    with_items:
      - grimshot
  - name: ensure that the screenshot dir exist
    file: path={{ ansible_env.HOME }}/Pictures/screenshots state=directory
  - name: copy the screenshot script
    become: yes
    template: src=../config/scripts/screenshot.tpl dest=/usr/local/bin/screenshot
  - name: ensure file that the script has the right permisions
    become: yes
    file: path=/usr/local/bin/screenshot owner=root group=root mode=0755
