---
#- import_playbook: subl.yml

- hosts: all
  tasks:
      - name: copy config
        template:
            src: ../config/configuration/Preferences.sublime-settings.tpl
            dest: /home/{{ ansible_env.USER }}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

