---
- hosts: all
  tasks:
      - name: copy config for high dpi
        vars:
          is_high_dpi: True
        template:
            src: ../config/configuration/Preferences.sublime-settings.tpl
            dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"

