---
- hosts: local
  tasks:
  - name: download sublime_text and check checksum
    get_url: 
      url: https://download.sublimetext.com/sublime_text_3_build_3126_x64.tar.bz2
      dest: /tmp/sublime_text.tar.bz2
      checksum: md5:acc34252b0ea7dff1f581c5db1564dcb
  - name: unpack sublime_text
    become: yes
    unarchive: src=/tmp/sublime_text.tar.bz2 dest=/usr/local/src/
  - name: create bin symlink
    become: yes
    file: src=/usr/local/src/sublime_text_3/sublime_text dest=/usr/local/bin/subl state=link
