---
- hosts: all
  tasks:
  - name: download sublime_text and check checksum
    get_url:
      url: https://download.sublimetext.com/sublime_text_build_4113_x64.tar.xz
      dest: /tmp/sublime_text.tar.xz
      checksum: md5:984f05273a97ad7fc9a9b7f8d7044dda
  - name: create directory to unpack
    become: yes
    ansible.builtin.file:
      path: /usr/local/src/sublime_text_4
      state: directory
  - name: unpack sublime_text
    become: yes
    unarchive: src=/tmp/sublime_text.tar.xz dest=/usr/local/src/sublime_text_4
  - name: create bin symlink
    become: yes
    ansible.builtin.file:
      src: /usr/local/src/sublime_text_4/sublime_text/sublime_text
      dest: /usr/local/bin/subl
      state: link
