---
- hosts: all
  tasks:
  - name: ensure that all dependencies are installed at the latest version
    become: yes
    package: state=latest name={{ item }}
    with_items:
      - terminator
  - name: ensure file that the config directory has the right permisions
    become: yes
    file:
      path: {{ ansible_env.HOME }}/.config/terminator
      state: directory
      owner: "{{ ansible_env.USERNAME }}"
      group: "{{ ansible_env.USERNAME }}"
      mode: 0755
  - name: copy main config
    template: src=../config/configuration/terminator.tpl dest={{ ansible_env.HOME }}/.config/terminator/config
