---
- hosts: all
  tasks:
  - name: ensure that all dependencies are installed at the latest version
    become: yes
    package: state=latest name={{ item }}
    with_items:
            - rofi
            - xclip
  - name: copy main config
    template: src=../config/configuration/symbols.txt dest=/home/{{ ansible_env.USER }}/.symbols.txt

