---
- hosts: all
  tasks:
  - name: ensure that all dependencies are installed at the latest version
    become: yes
    package: state=latest name={{ item }}
    with_items:
            - rofi
            - wl-clipboard
  - name: copy main config
    template: src=../config/configuration/symbols.txt dest={{ ansible_env.HOME }}/.symbols.txt

