---
- hosts: local
  tasks:
  - name: ensure that the vlc package is installed
    become: yes
    dnf: name=vlc state=present
  - name: ensure that the vlc mozilla package is installed
    become: yes
    dnf: name=mozilla-vlc state=present