---
- hosts: all
  tasks:
  - name: ensure zsh is installed at the latest version
    become: yes
    package: name=zsh state=latest
  - name: copy zsh config dir
    copy: src=../config/zsh/ dest=/home/{{ ansible_env.USER }}/.zsh/ 
  - name: download zsh-autosuggestions
    get_url:
      url: https://raw.githubusercontent.com/zsh-users/zsh-autosuggestions/master/zsh-autosuggestions.zsh
      dest: /home/{{ ansible_env.USER }}/.zsh/
  - name: copy main config
    template: src=../config/configuration/zshrc.tpl dest=/home/{{ ansible_env.USER }}/.zshrc
  - name: change default shell to zsh
    become: yes
    user: name={{ ansible_env.USER }} shell=/bin/zsh
    # You need to set $SHELL or logout and login again!
