---
- hosts: local
  tasks:
  - name: ensure zsh is installed at the latest version
    become: yes
    dnf: name=zsh state=latest
  - name: copy zsh config dir
    copy: src=../config/zsh/ dest=/home/l33tname/.zsh/ 
  - name: copy main config
    template: src=../config/configuration/zshrc.tpl dest=/home/l33tname/.zshrc
  - name: change default shell to zsh
    become: yes
    user: name=l33tname shell=/bin/zsh
    # You need to set $SHELL or logout and login again!
