---
# install vim
- hosts: local
  become: yes
  tasks:
  - name: ensure vim is installed at the latest version
    dnf: name=vim state=latest

# config git
- hosts: local
  tasks:
  - name: configure the git username
    git_config: name=user.name value="fliiiix" scope=global
  - name: configure the git email
    git_config: name=user.email value="de-ch@hotmail.de" scope=global
  - name: set the default push behavior to simple
    git_config: name=push.default value=simple scope=global

# install icon set
- hosts: local
  tasks:
  - name: ensure librsvg2-tools is installed at the latest version
    become: yes
    dnf: name=librsvg2-tools state=latest
    # https://github.com/ansible/ansible-modules-core/issues/5592
  - name: ensure that the .icons/Clarity dir don't exist
    file: path=/home/l33tname/.icons/Clarity state=absent
  - name: clone icons
    git: repo=https://github.com/jcubic/Clarity.git force=yes dest=/home/l33tname/.icons/Clarity
  - name: config icons
    command: ./configure chdir=/home/l33tname/.icons/Clarity
  - name: build icons
    command: make luteus chdir=/home/l33tname/.icons/Clarity

# setup sreenshot script
- hosts: local
  tasks:
  - name: ensure scrot is installed at the latest version
    become: yes
    dnf: name=scrot state=latest
    # used for file permisions not sure why ^^ 
  - name: ensure libselinux-python is installed at the latest version
    become: yes
    dnf: name=libselinux-python state=latest
  - name: ensure that the screenshot dir exist
    file: path=/home/l33tname/Pictures/screenshots state=directory
  - name: copy the screenshot script
    become: yes
    template: src=config/scripts/screenshot.tpl dest=/usr/local/bin/screenshot
  - name: ensure file that the script has the right permisions
    become: yes
    file: path=/usr/local/bin/screenshot owner=root group=root mode=0755

# install mtpaint
- hosts: local
  tasks:
    - name: ensure mtpaint is installed at the latest version
      become: yes
      dnf: name=mtpaint state=latest

# install sublimetext 
- hosts: local
  tasks:
    - name: download sublime_text and check checksum
      get_url: 
        url: https://download.sublimetext.com/sublime_text_3_build_3126_x64.tar.bz2
        dest: /tmp/sublime_text.tar.bz2
        checksum: md5:acc34252b0ea7dff1f581c5db1564dcb
    - name: ensure that the extration dir exist
      become: yes
      file: path=/usr/local/sublime_text_3 state=directory
    - name: unpack sublime_text
      become: yes
      unarchive: src=/tmp/sublime_text.tar.bz2 dest=/usr/local/src/sublime_text_3
